### ISSUE TITLE
Regularly auto committing

### ISSUE THREAD

**Issue by yorrd** [silverbulletmd/silverbullet-git#1]
The git plugin in Obsidian provides a feature which automatically commits every x minutes. Is this something that's in scope for this plugin? I might try to contribute if that's something you're open to.

**Comment by zefhemel** [comment]
Definitely, especially if you make it configurable via a setting in `SETTINGS`.

**Comment by jamesob** [comment]
I think it would be best to commit after some "debounce" period, if possible. I.e. last file change happened `n` minutes ago, commit then.

**Comment by zefhemel** [comment]
Practical implementation issue here may be that if the client triggers the commit, the window may have been closed within those x minutes since the last change. A simpler implementation may be to just auto commit every n minutes anyway, where no changes would simply result in a "no op."

**Comment by zefhemel** [comment]
Ok, this is now implemented. Update your plug to get the feature and see the README on how to configure it: https://silverbullet.md/%F0%9F%94%8C%20Git

**Comment by jamesob** [comment]
Very cool! Will try this out soon. Thank you.
