### ISSUE TITLE
Non-github repositories

### ISSUE THREAD

**Issue by crawfordlong** [silverbulletmd/silverbullet-git#5]
Does this plugin support non-Github repositories (_e.g._, gitea, gitlab, etc.)?

**Comment by crawfordlong** [comment]
Ok, I think I answered my own question (sorry). I didn't see it at first, but this appears to be using local git commands to perform actions on the local repository, including pushing to whatever is set as the destination in the repo config. Am I reading that right?

**Comment by zefhemel** [comment]
Yes. Other than the one GitHub specific command, it has no awareness of underlying git hosting and just does command line git commits, pulls and pushes.
